### ISSUE TITLE
Better landing page

### ISSUE THREAD

**Issue by jasonharrison** [flamecoals/turnato#27]
We should consider improving the landing page.  The landing page has a lot of white space to the left/right of the content:

![Landing page with a lot of unused space](https://i.imgur.com/z7jwPCH.png)

**Comment by flamecoals** [comment]
I am focusing the development effort in mobile devices first, so right now this is expected in desktop. 
I want to make desktop functional but it is not the highest priority for it to be pretty. I think we should focus on this only after having a great mobile experience, so I am closing it for now.

**Comment by jasonharrison** [comment]
Then we should move this issue to the icebox, which is a backlog of ideas that we know aren't going to be worked on soon.  We'll keep this issue in the icebox because it's possible we'll work on the desktop layout in the future.
